baseURL = 'https://tsesc.github.io/jackblog/'
languageCode = 'zh-tw'
title = 'Jack Blog'
theme = 'PaperMod'

[pagination]
pagerSize = 5

[params]
env = 'production'
title = 'Jack Blog'
description = 'æˆ‘çš„å€‹äººéƒ¨è½æ ¼'
keywords = ['Blog', 'Portfolio', 'PaperMod']
author = 'Jack Tse'
defaultTheme = 'auto'
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.assets]
favicon = '<link / abs url>'
favicon16x16 = '<link / abs url>'
favicon32x32 = '<link / abs url>'
apple_touch_icon = '<link / abs url>'
safari_pinned_tab = '<link / abs url>'

[params.label]
text = 'Home'
icon = '/apple-touch-icon.png'
iconHeight = 35

[params.profileMode]
enabled = false
title = 'Jack Blog'
subtitle = 'æ­¡è¿ä¾†åˆ°æˆ‘çš„éƒ¨è½æ ¼'
imageUrl = '<img location>'
imageWidth = 120
imageHeight = 120
imageTitle = 'my image'

[[params.profileMode.buttons]]
name = 'Posts'
url = 'posts'

[[params.profileMode.buttons]]
name = 'Tags'
url = 'tags'

[params.homeInfoParams]
Title = 'æ­¡è¿ä¾†åˆ° Jack çš„éƒ¨è½æ ¼ ğŸ‘‹'
Content = 'åˆ†äº«æŠ€è¡“ã€ç”Ÿæ´»èˆ‡æƒ³æ³•çš„åœ°æ–¹'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/'

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/'

[params.analytics.google]
SiteVerificationTag = 'XYZabc'

[params.analytics.bing]
SiteVerificationTag = 'XYZabc'

[params.analytics.yandex]
SiteVerificationTag = 'XYZabc'

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = 'https://github.com/<path_to_repo>/content'
Text = 'Suggest Changes'
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ['title', 'permalink', 'summary', 'content']

[[menu.main]]
identifier = 'categories'
name = 'åˆ†é¡'
url = '/categories/'
weight = 10

[[menu.main]]
identifier = 'tags'
name = 'æ¨™ç±¤'
url = '/tags/'
weight = 20

[[menu.main]]
identifier = 'archives'
name = 'æ­¸æª”'
url = '/archives/'
weight = 30

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
style = 'monokai'